export const countries = {
	"American Samoa": "AS",
	"Andorra": "AD",
	"Argentina": "AR",
	"Australia": "AU",
	"Austria": "AT",
	"Bangladesh": "BD",
	"Belgium": "BE",
	"Brazil": "BR",
	"Bulgaria": "BG",
	"Canada": "CA",
	"Croatia": "HR",
	"Czech Republic": "CZ",
	"Denmark": "DK",
	"Dominican Republic": "DO",
	"Faroe Islands": "FO",
	"Finland": "FI",
	"France": "FR",
	"French Guyana": "GF",
	"French Reunion": "RE",
	"Germany": "DE",
	"Great Britain": "GB",
	"Greenland": "GL",
	"Guadeloupe": "GP",
	"Guam": "GU",
	"Guatemala": "GT",
	"Guernsey": "GG",
	"Guyana": "GY",
	"Holland": "NL",
	"Hungary": "HU",
	"Iceland": "IS",
	"India": "IN",
	"Isle of Man": "IM",
	"Italy": "IT",
	"Japan": "JP",
	"Jersey": "JE",
	"Liechtenstein": "LI",
	"Lithuania": "LT",
	"Luxembourg": "LU",
	"Macedonia": "MK",
	"Malaysia": "MY",
	"Marshall Islands": "MH",
	"Martinique": "MQ",
	"Mayotte": "YT",
	"Mexico": "MX",
	"Moldavia": "MD",
	"Monaco": "MC",
	"New Zealand": "NZ",
	"Northern Mariana Islands": "MP",
	"Norway": "NO",
	"Pakistan": "PK",
	"Phillippines": "PH",
	"Poland": "PL",
	"Portugal": "PT",
	"Puerto Rico": "PR",
	"Russia": "RU",
	"Saint Pierreand Miquelon": "PM",
	"San Marino": "SM",
	"Slovak Republic": "SK",
	"Slovenia": "SI",
	"South Africa": "ZA",
	"Spain": "ES",
	"SriLanka": "LK",
	"Svalbard&JanMayen Islands": "SJ",
	"Sweden": "SE",
	"Switzerland": "CH",
	"Thailand": "TH",
	"Turkey": "TR",
	"United States": "US",
	"Vatican": "VA",
	"Virgin Islands": "VI"
}